// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvhdanOEso1jfT74A5DKS2WRhk7owu3Zw',
    appId: '1:123209206383:web:23e20646720be8434a9b9a',
    messagingSenderId: '123209206383',
    projectId: 'chatbot-testing-e1ea9',
    authDomain: 'chatbot-testing-e1ea9.firebaseapp.com',
    storageBucket: 'chatbot-testing-e1ea9.appspot.com',
    measurementId: 'G-MBS36DFEH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrNEdZsqOdYGauWIm3F3xZlYZFakLfhNA',
    appId: '1:123209206383:android:d5731709a41212994a9b9a',
    messagingSenderId: '123209206383',
    projectId: 'chatbot-testing-e1ea9',
    storageBucket: 'chatbot-testing-e1ea9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuQvFGQ7HkP3uyaO72BB6d9IOa3LOKqnA',
    appId: '1:123209206383:ios:543e6bda058a6ac34a9b9a',
    messagingSenderId: '123209206383',
    projectId: 'chatbot-testing-e1ea9',
    storageBucket: 'chatbot-testing-e1ea9.appspot.com',
    iosBundleId: 'com.example.chatboat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuQvFGQ7HkP3uyaO72BB6d9IOa3LOKqnA',
    appId: '1:123209206383:ios:543e6bda058a6ac34a9b9a',
    messagingSenderId: '123209206383',
    projectId: 'chatbot-testing-e1ea9',
    storageBucket: 'chatbot-testing-e1ea9.appspot.com',
    iosBundleId: 'com.example.chatboat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvhdanOEso1jfT74A5DKS2WRhk7owu3Zw',
    appId: '1:123209206383:web:9f112565980b75614a9b9a',
    messagingSenderId: '123209206383',
    projectId: 'chatbot-testing-e1ea9',
    authDomain: 'chatbot-testing-e1ea9.firebaseapp.com',
    storageBucket: 'chatbot-testing-e1ea9.appspot.com',
    measurementId: 'G-Z5B87D4E4S',
  );
}
